### ISSUE TITLE
Backup notifications

### ISSUE THREAD

**Issue by Toolhead** [sanderdw/hassio-addons#10]
Have the add-on running for almost a month without problems.
Since a few days getting notifications concerning backups.
Did not change any settings.
Backup folder is set to /backup/dsmrreader

**Comment by ewoutdenheijer** [comment]
The problem seems to be with conflicting versions of Postgres:
(OSError) dsmr_backup.services.backup.run errored: b'pg_dump: server version: 12.4; pg_dump version: 11.10 (Debian 11.10-0+deb10u1)\npg_dump: aborting because of server version mismatch\n'

Off course the TimescaleDB addon wil get backed up if you use Google Drive Backup anyway...

**Comment by sanderdw** [comment]
It's related [to this issue](https://github.com/xirixiz/dsmr-reader-docker/issues/180). There is a fix on the way, so expect an update in the coming days.

**Comment by sanderdw** [comment]
@Toolhead , @ewoutdenheijer just released DSMR Reader 0.1.2. Can you check if it's fixed now?

**Comment by ewoutdenheijer** [comment]
Seems to be working now. At least, i can make a backup using:
. /app/bash.sh
./manage.py dsmr_backup_create --compact

Thanks!
